# Generated by Django 5.2.8 on 2025-11-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructorApp', '0006_module_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
