# Generated by Django 5.2.8 on 2025-11-22 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructorApp', '0009_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='course_instances',
        ),
        migrations.AddField(
            model_name='order',
            name='cart_instances',
            field=models.ManyToManyField(related_name='order', to='instructorApp.cart'),
        ),
    ]
