# Generated by Django 5.2.8 on 2025-11-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructorApp', '0010_remove_order_course_instances_order_cart_instances'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_instances',
        ),
        migrations.AddField(
            model_name='order',
            name='course_instances',
            field=models.ManyToManyField(related_name='order', to='instructorApp.course'),
        ),
    ]
